### ISSUE TITLE
Version 9.3.5 onwards breaks my documentation

### ISSUE THREAD

**Issue by zap2zero** [rapi-doc/RapiDoc#1027] opened 2024-09-21 13:15 UTC
Hello there,

so far I have bin using https://unpkg.com/rapidoc/dist/rapidoc-min.js in my index.html to source RapiDoc but with the latest versions (9.3.5+), my documents no longer render. 

When I source https://unpkg.com/rapidoc@9.3.4/dist/rapidoc-min.js everything is working nicely.

The API can be found at https://api.eve-scout.com/ui/ and the yaml which I load in the index.html is https://api.eve-scout.com/ui/openapi.yaml

**Comment by mrin9** [comment] 2024-09-21 17:47
can you confirm me that it is broken in `v9.3.6` as well

also the spec you have provided  https://api.eve-scout.com/ui/openapi.yaml is a split spec
the `paths`, `schemas`  and `components` are defined in other `yaml`s

Split files are not a problem as you can see the [split-file-test-case](https://rapidocweb.com/examples/external-refs.html) works. 
but due to this I am unable to test or recreate your issue at my end, further the files are blocked by `CORS`. So can you provide me with small reproducible spec(s) so that i can further work on it

**Comment by zap2zero** [comment] 2024-09-21 20:27
First off, thanks for the fast reply!

I can confirm that 9.3.6 is also broken for me - thats how I noticed since the live page refers to latest and stopped working.

Here is my full openapi directory with all my yaml files.
[evescout-api-docs.tar.gz](https://github.com/user-attachments/files/17085655/evescout-api-docs.tar.gz)

**Comment by mrin9** [comment] 2024-09-22 13:47
Are you using any tool or generator to split the OpenAPI spec ? coz the way its splitting the spec is not valid

for instance in your OpenAPI  Spec the `paths` have a `$ref` pointer and it is not a valid location

```yml
paths:
  $ref: "./paths/_index.yaml"
```
when I fixed one of the ref it worked. in `v9.3.5` + we updated our OpenAPI parser which is more compliant to the standard 
  
You may refer to [this](https://swagger.io/docs/specification/using-ref/#:~:text=A%20common%20misconception%20is%20that,openapi%3A%203.0.) 

<img width="979" alt="image" src="https://github.com/user-attachments/assets/07c6fc67-1686-48a2-b6ae-91dffcee21fc">

**Comment by zap2zero** [comment] 2024-09-22 19:42
My docs are not generated, I wrote them all by hand. I'll look into this tomorrow and see if I can get this fixed.

Thanks for looking into this!

**Comment by mrin9** [comment] 2024-09-23 12:08
closing this one...feel free to open a new one and link this issue there in case u find anything incorrect

**Closed by mrin9** 2024-09-23 12:08 UTC
