### ISSUE TITLE
Vue 3: I get exception Cannot read properties of null (reading 'loadSpec') 

### ISSUE THREAD

**Issue by danielSenpaiDev** [rapi-doc/RapiDoc#931] opened 2023-06-01 00:54 UTC
Hi!
I tried to use rapi-doc on my Vue 3 project, and although it works basically with the spec-url attribute (for example: http://localhost/swagger.json), I get issues when tried to use the API method loadSpec() when I try to load the JSON object programatically, which is an OpenAPI spec. I get the exception

```
Cannot read properties of null (reading 'loadSpec')
TypeError: Cannot read properties of null (reading 'loadSpec')
    at Proxy.showTab2 (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/ArtifactDetail.vue?vue&type=script&lang=js:45:46)
    at onClick._cache.<computed>._cache.<computed> (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/ArtifactDetail.vue?vue&type=template&id=6d689bfd&scoped=true:156:83)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:285:18)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:293:17)
    at HTMLDivElement.invoker (webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:425:82)
```

I started using rapi-doc as the example for Vue 3 the same way inside a file named ApiView.vue. The idea is to populate the open api spec programatically:

```
<template>
<!-- other <divs> here that act like tabs -->
<div @click="showTab2()">
<rapi-doc id="theApi"  render-style = "read"   style = "height:100vh; width:100%"  > </rapi-doc>
</div>
</template>

import 'rapidoc';

export default {
    name: "ApiView",
    mounted() {
      axios.get('http://localhost:3000/api')
      .then(response => {
        this.api=response.data;
      });
    },
    created() { },
    data() {
        return {
          tab1Display: true,
          tab2Display : false,
          tab3Display: false,
          api:{}
        };
    },
    props: [ 'group', 'artifactName', 'version' ],
    methods: {
      showTab1() {
        this.tab1Display = true;
        this.tab2Display = false;
        this.tab3Display = false;
      },
      showTab2() {
        // this is the shortest valid OAS3 spec that I can write
        var oas = `{
             "openapi": "3.0.2",
              "info": {
                 "title": "test",
                 "version": "1.0.0"
               },
              "paths": {
                 "/test": {}
               }
       }`;
      
      let obj = JSON.parse(oas);
      document.getElementById('theApi').loadSpec(obj);  // <--- ERROR HERE
        
        this.tab1Display = false;
        this.tab2Display = true;
        this.tab3Display = false;
      },

      showTab3() {
        this.tab1Display = false;
        this.tab2Display = false;
        this.tab3Display = true;
      }
    }
};
</script>
```
I know I can pass the object directly instead of parsing it from a string, I was just doing some test. It failed too.

The idea is when I click the Tab inside the rapi-doc element is, it loads the spec that was already gotten from the mounted() function. I tried moving the loadSpec to mounted but no luck. I got the same exception.

Maybe I'm missing something that I dodn't realize.

Could you guys give me a hand, please?

**Comment by mrin9** [comment] 2023-07-18 04:41
the issue is `document.getElementById('theApi')` is resulting into `null` this is a pure HTML/JS issue . you need to figure out why thats resolving to `null`. Once you fix that then `loadSpec()`  should work

**Closed by mrin9** 2023-07-18 04:41 UTC
