### ISSUE TITLE
Is it possible to prevent responses from being reset

### ISSUE THREAD

**Issue by gmeister2** [rapi-doc/RapiDoc#764] opened 2022-06-02 14:12 UTC
Is it possible to prevent the reset of the response textarea, when you switch between endpoints (render-style: focused).

version: 9.3.2

Procedure:

- click on endpoint 1
- click on button 'try'
- look at response textarea 1
- click on endpoint 2
- click on button 'try'
- look at response textarea 2
- click on endpoint 1
- look at response textarea 1
- click on endpoint 2
- look at response textarea 2
- ...

i.e. being able to quickly compare the response from different endpoints by only clicking on the endpoints in the navigation, without the response being automatically cleared

**Comment by mrin9** [comment] 2022-06-03 00:09
this is an existing problem with `render-style="focused"` #726 
It is a technical issue where we may have to move few things a bit.

I am not able to provide a fix anytime soon but have plans to get to it at some point 

The other option would be to move to `render-style=read` which do not uses separate textarea for different endpoint
closing this one as its a duplicate of #726

**Closed by mrin9** 2022-06-03 00:09 UTC

**Comment by gmeister2** [comment] 2022-06-03 06:59
Thanks for your answer.

I think there might be a small mixup, in that your answer seems to belong to another posting that I made (https://github.com/rapi-doc/RapiDoc/issues/763).

**Comment by mrin9** [comment] 2022-06-19 05:10
yes was a mistake , that comment was for #763 

For this issue. We store the example state on the DOM itself. 
In focused mode we destroy the DOM as soon as you move away from one endpoint to another. This is to keep the DOM size smaller and helps for larger specs.

However if you need to store the examples state then use `read` mode instead. Each mode brings in its own pros and cons so use the one that best suits your need.

> PS:
We do have plans to store state outside of DOM in focused mode. this will need us to build a state complete management solution. it will be maintaining state for all the endpoints you change and not just the previous one. However this is more of a feature rather than a fix and we have'nt allocated any timing for this
