### ISSUE TITLE
Overridden description / summary of reference objects not shown

### ISSUE THREAD

**Issue by tib-c** [rapi-doc/RapiDoc#971] opened 2023-10-30 13:44 UTC
A response "myResponse" is defined in the components section of the spec. In the path "myPath" it is referenced within the "get"-operations response 200. As described in the [spec](https://spec.openapis.org/oas/v3.1.0#referenceObject) the fields "summary" and "description" can be overidden when a reference object is used. In the following example, the description of the reference is overridden with a local description. 

```
{
  "openapi": "3.1.0",
  "info": {
    "title": "BUG API",
    "version": "1.0"
  },
  "paths": {
    "/myPath": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/components/responses/myResponse",
            "description": "Override description where used"
          }
        }
      }
    }
  },
  "components": {
    "responses": {
      "myResponse": {
        "description": "Original description from component"
      }
    }
  }
}
```

Rendered by RapiDoc:
![grafik](https://github.com/rapi-doc/RapiDoc/assets/128486915/f8847a88-7343-4852-8fcc-8599bacfe4b2)

Current behaviour: RapiDoc renders the description from the component
Correct behaviour: The local description should be shown.

The field "summary" is not available for response objects, so it only concerns the description. Other component types were not tested yet, as that might occur for other types too.

**Comment by mrin9** [comment] 2024-09-21 00:05
closing as its a duplicate of #720

**Closed by mrin9** 2024-09-21 00:05 UTC
