### ISSUE TITLE
Feature Request - Pass body params through text input along with textarea??

### ISSUE THREAD

**Issue by nikitapatel029** [rapi-doc/RapiDoc#814] opened 2022-09-05 10:26 UTC
Hey Team,

I have one requirement where I wanted to give text input to user where they can pass few params and along wiht that wanted to show entire body json in text area as well.
suppose input json is 
{
"amount":123,
"account_num":"123,
"xyz":"static value",
.
.
"test":"Static value"
}
Here I wanted to ask amount attributes from user only, others parmeters I wanted to pass as static one so will keep one text input where developer can pass amount and other side it will affect in text area where we can show entire body json with static params and this one

as an example:  https://testcps.readme.io/reference/updatefeature
How they are updating right side in example bar, same way I want to update in example text area with entire json body(that text are would be readable format but will pass this entire body while click on TRY OUT button).

Thanks in advance.

**Comment by mrin9** [comment] 2022-09-08 20:04
duplicate of #818

**Closed by mrin9** 2022-09-08 20:04 UTC
