### ISSUE TITLE
Self-contained CSS in RapiDoc-min

### ISSUE THREAD

**Issue by villanella** [rapi-doc/RapiDoc#976] opened 2023-11-15 09:41 UTC
Problem: embed Rapidoc-min overlaps the borders of containers in target web interface.

![photo_5377674714362794050_x](https://github.com/rapi-doc/RapiDoc/assets/4890566/ffd4cfdb-0201-490c-bb9a-8a675ef8219a)
![pic-selected-231029-1518-15 (1)](https://github.com/rapi-doc/RapiDoc/assets/4890566/616ab325-6e60-49fe-82e3-42ffff28f1c7)

Because RapiDoc-min widget is designed for integration into other systems, its CSS should be self-contained and not rely on a surrounding context.

See the related issue about visual problems in RapiDoc-StrictDoc integration: https://github.com/strictdoc-project/strictdoc/issues/1400

**Comment by mrin9** [comment] 2024-09-26 00:37
`<rapi-doc-mini>` needs a minimum of `360px` width.

Given the above screenshots it is not clear is the issue is due to the styles applied on the host document or due to RapiDocs css

I will be closing this one, If this is still an issue please reopen another one providing an minimal `html` file to recreate it at my end

**Closed by mrin9** 2024-09-26 00:37 UTC
